name: "Azure Login"
description: "Login to Azure using service principal credentials"
outputs:
  AZURE_DEPLOY_CREDENTIALS:
    description: "Azure deployment credentials as JSON string"
    value: ${{ steps.compute_azure_creds.outputs.AZURE_DEPLOY_CREDENTIALS }}
runs:
  using: "composite"
  steps:
    - name: Compute Azure Credentials
      id: compute_azure_creds
      run: |
        echo 'AZURE_DEPLOY_CREDENTIALS<<EOF' >> $GITHUB_OUTPUT
        echo '{' >> $GITHUB_OUTPUT
        echo '  "clientId": "${{ secrets.AZURE_DEPLOY_CLIENT_ID }}",' >> $GITHUB_OUTPUT
        echo '  "clientSecret": "${{ secrets.AZURE_DEPLOY_CLIENT_SECRET }}",' >> $GITHUB_OUTPUT
        echo '  "subscriptionId": "${{ secrets.AZURE_DEPLOY_SUBSCRIPTION_ID }}",' >> $GITHUB_OUTPUT
        echo '  "tenantId": "${{ secrets.AZURE_DEPLOY_TENANT_ID }}"' >> $GITHUB_OUTPUT
        echo '}' >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ steps.compute_azure_creds.outputs.AZURE_DEPLOY_CREDENTIALS }}
